services:
  flask_app:
    container_name: YouTube-MP3-Downloader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:  ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]
