version: "3.9"

services:
  flask_app:
    container_name: YouTube-MP3-Downloader
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command:  ["python", "app.py"]